
spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true
server:
  port: 14000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


zuul:
  routes:
    apple:
      path: /apple/**
      serviceId: apple-server
      strip-prefix: false
