server:
  port: 9000
  http2:
    enabled: true
spring:
#  main:
#    allow-bean-definition-overriding: true
  application:
    name: web
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
feign:
  hystrix:
    enabled: true


ribbon:
  ReadTimeout:  30000
  ConnectTimeout:  15000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000


