server:
  port: 8769
spring:
  application:
    name: service-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
      strip-prefix: true
    api-b:
      path: /api-b/**
      serviceId: SERVICE-FEIGN
      strip-prefix: true
