server:
  port: 8765
spring:
  application:
    name: service-feign
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



#feign默认自带断路器，D版本以后默认没有打开，需要配置开启断路器
feign:
  hystrix:
    enable: true